// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCQWNTOa2rEogaPVRVNI0nZNHIUOkNiv8Q',
    appId: '1:231612704070:web:c7de5cab7fe1b7cf11b147',
    messagingSenderId: '231612704070',
    projectId: 'fir-63bdb',
    authDomain: 'fir-63bdb.firebaseapp.com',
    storageBucket: 'fir-63bdb.appspot.com',
    measurementId: 'G-THFB2KTR69',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAVMWHDRP6t9L7o4WQNfYlFEY4zGO_6Lhk',
    appId: '1:231612704070:android:addf28108caeb31611b147',
    messagingSenderId: '231612704070',
    projectId: 'fir-63bdb',
    storageBucket: 'fir-63bdb.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAm5cXM5clFtxwdYZ2EnEPPvGBSijC1pj8',
    appId: '1:231612704070:ios:3abd1025ace067ff11b147',
    messagingSenderId: '231612704070',
    projectId: 'fir-63bdb',
    storageBucket: 'fir-63bdb.appspot.com',
    iosBundleId: 'com.example.firebase',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAm5cXM5clFtxwdYZ2EnEPPvGBSijC1pj8',
    appId: '1:231612704070:ios:3abd1025ace067ff11b147',
    messagingSenderId: '231612704070',
    projectId: 'fir-63bdb',
    storageBucket: 'fir-63bdb.appspot.com',
    iosBundleId: 'com.example.firebase',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCQWNTOa2rEogaPVRVNI0nZNHIUOkNiv8Q',
    appId: '1:231612704070:web:2dd6d6caaf4c732411b147',
    messagingSenderId: '231612704070',
    projectId: 'fir-63bdb',
    authDomain: 'fir-63bdb.firebaseapp.com',
    storageBucket: 'fir-63bdb.appspot.com',
    measurementId: 'G-7C2711N17F',
  );
}
